// generated by tools::package_native_routine_registration_skeleton(".")
// see https://github.com/RcppCore/Rcpp/issues/636

#include <R.h>
#include <Rinternals.h>
#include <stdlib.h> // for NULL
#include <R_ext/Rdynload.h>

/* .Call calls */
extern SEXP genepop_getVersion();
extern SEXP genepop_RAnalyzingSingleContingencyTable(SEXP, SEXP, SEXP, SEXP);
extern SEXP genepop_RAnalyzingSingleContingencyTableWithSettingsFile(SEXP, SEXP);
extern SEXP genepop_RConversionToIndividualDataWithIndividualNames(SEXP, SEXP);
extern SEXP genepop_RConversionToIndividualDataWithPopulationNames(SEXP, SEXP);
extern SEXP genepop_RDescriptifAlleleAndGenotypeFrequenciesPerLocusPerSample(SEXP, SEXP);
extern SEXP genepop_RDescriptifGeneDiversitiesAndFisUsingAlleleIdentity(SEXP, SEXP, SEXP);
extern SEXP genepop_RDescriptifGeneDiversitiesAndFisUsingAlleleSize(SEXP, SEXP, SEXP);
extern SEXP genepop_RDiploidisationHaploidData(SEXP, SEXP);
extern SEXP genepop_REcumenicismBiosysLetter(SEXP, SEXP);
extern SEXP genepop_REcumenicismBiosysNumber(SEXP, SEXP);
extern SEXP genepop_REcumenicismFstat(SEXP, SEXP);
extern SEXP genepop_REcumenicismLinkdos(SEXP, SEXP);
//extern SEXP genepop_resetSeed();
extern SEXP genepop_REstimatingSpatialStructureAlleleIdentyAllPopulations(SEXP, SEXP, SEXP);
extern SEXP genepop_REstimatingSpatialStructureAlleleIdentyAllPopulationsPairs(SEXP, SEXP, SEXP);
extern SEXP genepop_REstimatingSpatialStructureAlleleSizeAllPopulations(SEXP, SEXP, SEXP);
extern SEXP genepop_REstimatingSpatialStructureAlleleSizeAllPopulationsPairs(SEXP, SEXP, SEXP);
extern SEXP genepop_RGDEachPairLociEachPopulation(SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP genepop_RGDEachPairLociEachPopulationWithSettingsFile(SEXP, SEXP, SEXP);
extern SEXP genepop_RGDGenotypicContingency(SEXP, SEXP);
extern SEXP genepop_RHWEachLocusEachPopulationHD(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP genepop_RHWEachLocusEachPopulationHDWithSettingsFile(SEXP, SEXP, SEXP);
extern SEXP genepop_RHWEachLocusEachPopulationHE(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP genepop_RHWEachLocusEachPopulationHEWithSettingsFile(SEXP, SEXP, SEXP);
extern SEXP genepop_RHWEachLocusEachPopulationProbability(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP genepop_RHWEachLocusEachPopulationProbabilityWithSettingsFile(SEXP, SEXP, SEXP);
extern SEXP genepop_RHWGlobalHD(SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP genepop_RHWGlobalHDWithSettingsFile(SEXP, SEXP, SEXP);
extern SEXP genepop_RHWGlobalHE(SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP genepop_RHWGlobalHEWithSettingsFile(SEXP, SEXP, SEXP);
extern SEXP genepop_RHWtableAlleleFrequenciesExpectedGenotypesFis(SEXP);
extern SEXP genepop_RHWtableHD(SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP genepop_RHWtableHDWithSettingsFile(SEXP, SEXP);
extern SEXP genepop_RHWtableHE(SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP genepop_RHWtableHEWithSettingsFile(SEXP, SEXP);
extern SEXP genepop_RHWtableProbability(SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP genepop_RHWtableProbabilityWithSettingsFile(SEXP, SEXP);
extern SEXP genepop_Rinterrupt_genepop();
extern SEXP genepop_RIsolationByDistanceBetweenGroups(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP genepop_RIsolationByDistanceBetweenGroupsWithSettingsFile(SEXP, SEXP, SEXP);
extern SEXP genepop_RIsolationByDistanceBetweenIndividuals(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP genepop_RIsolationByDistanceBetweenIndividualsWithSettingsFile(SEXP, SEXP, SEXP);
extern SEXP genepop_RNmEstimates(SEXP, SEXP, SEXP);
extern SEXP genepop_RNullAlleleEstimateAlleleFrequencies(SEXP, SEXP, SEXP, SEXP);
extern SEXP genepop_RNullAlleleEstimateAlleleFrequenciesWithSettingsFile(SEXP, SEXP, SEXP);
extern SEXP genepop_RPDGenicAllPairPopulationDifferentiation(SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP genepop_RPDGenicAllPairPopulationDifferentiationWithSettingsFile(SEXP, SEXP, SEXP);
extern SEXP genepop_RPDGenicAllPopulationDifferentiation(SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP genepop_RPDGenicAllPopulationDifferentiationWithSettingsFile(SEXP, SEXP, SEXP);
extern SEXP genepop_RPDGenotypicAllPairPopulationDifferentiation(SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP genepop_RPDGenotypicAllPairPopulationDifferentiationWithSettingsFile(SEXP, SEXP, SEXP);
extern SEXP genepop_RPDGenotypicAllPopulationDifferentiation(SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP genepop_RPDGenotypicAllPopulationDifferentiationWithSettingsFile(SEXP, SEXP, SEXP);
extern SEXP genepop_RRandomSamplingOfHaploidGenotypesFromDiploidOnes(SEXP, SEXP);
extern SEXP genepop_RRelabelingAlleles(SEXP, SEXP);
extern SEXP genepop_Rset_restriction(SEXP);
extern SEXP genepop_setMantelSeed(SEXP);
extern SEXP genepop_setRandomSeed(SEXP);

static const R_CallMethodDef CallEntries[] = {
  {"genepop_getVersion",                                                   (DL_FUNC) &genepop_getVersion,                                                    0},
  {"genepop_RAnalyzingSingleContingencyTable",                             (DL_FUNC) &genepop_RAnalyzingSingleContingencyTable,                              4},
  {"genepop_RAnalyzingSingleContingencyTableWithSettingsFile",             (DL_FUNC) &genepop_RAnalyzingSingleContingencyTableWithSettingsFile,              2},
  {"genepop_RConversionToIndividualDataWithIndividualNames",               (DL_FUNC) &genepop_RConversionToIndividualDataWithIndividualNames,                2},
  {"genepop_RConversionToIndividualDataWithPopulationNames",               (DL_FUNC) &genepop_RConversionToIndividualDataWithPopulationNames,                2},
  {"genepop_RDescriptifAlleleAndGenotypeFrequenciesPerLocusPerSample",     (DL_FUNC) &genepop_RDescriptifAlleleAndGenotypeFrequenciesPerLocusPerSample,      2},
  {"genepop_RDescriptifGeneDiversitiesAndFisUsingAlleleIdentity",          (DL_FUNC) &genepop_RDescriptifGeneDiversitiesAndFisUsingAlleleIdentity,           3},
  {"genepop_RDescriptifGeneDiversitiesAndFisUsingAlleleSize",              (DL_FUNC) &genepop_RDescriptifGeneDiversitiesAndFisUsingAlleleSize,               3},
  {"genepop_RDiploidisationHaploidData",                                   (DL_FUNC) &genepop_RDiploidisationHaploidData,                                    2},
  {"genepop_REcumenicismBiosysLetter",                                     (DL_FUNC) &genepop_REcumenicismBiosysLetter,                                      2},
  {"genepop_REcumenicismBiosysNumber",                                     (DL_FUNC) &genepop_REcumenicismBiosysNumber,                                      2},
  {"genepop_REcumenicismFstat",                                            (DL_FUNC) &genepop_REcumenicismFstat,                                             2},
  {"genepop_REcumenicismLinkdos",                                          (DL_FUNC) &genepop_REcumenicismLinkdos,                                           2},
  //{"genepop_resetSeed",                                                    (DL_FUNC) &genepop_resetSeed,                                                     0},
  {"genepop_REstimatingSpatialStructureAlleleIdentyAllPopulations",        (DL_FUNC) &genepop_REstimatingSpatialStructureAlleleIdentyAllPopulations,         3},
  {"genepop_REstimatingSpatialStructureAlleleIdentyAllPopulationsPairs",   (DL_FUNC) &genepop_REstimatingSpatialStructureAlleleIdentyAllPopulationsPairs,    3},
  {"genepop_REstimatingSpatialStructureAlleleSizeAllPopulations",          (DL_FUNC) &genepop_REstimatingSpatialStructureAlleleSizeAllPopulations,           3},
  {"genepop_REstimatingSpatialStructureAlleleSizeAllPopulationsPairs",     (DL_FUNC) &genepop_REstimatingSpatialStructureAlleleSizeAllPopulationsPairs,      3},
  {"genepop_RGDEachPairLociEachPopulation",                                (DL_FUNC) &genepop_RGDEachPairLociEachPopulation,                                 5},
  {"genepop_RGDEachPairLociEachPopulationWithSettingsFile",                (DL_FUNC) &genepop_RGDEachPairLociEachPopulationWithSettingsFile,                 3},
  {"genepop_RGDGenotypicContingency",                                      (DL_FUNC) &genepop_RGDGenotypicContingency,                                       2},
  {"genepop_RHWEachLocusEachPopulationHD",                                 (DL_FUNC) &genepop_RHWEachLocusEachPopulationHD,                                  6},
  {"genepop_RHWEachLocusEachPopulationHDWithSettingsFile",                 (DL_FUNC) &genepop_RHWEachLocusEachPopulationHDWithSettingsFile,                  3},
  {"genepop_RHWEachLocusEachPopulationHE",                                 (DL_FUNC) &genepop_RHWEachLocusEachPopulationHE,                                  6},
  {"genepop_RHWEachLocusEachPopulationHEWithSettingsFile",                 (DL_FUNC) &genepop_RHWEachLocusEachPopulationHEWithSettingsFile,                  3},
  {"genepop_RHWEachLocusEachPopulationProbability",                        (DL_FUNC) &genepop_RHWEachLocusEachPopulationProbability,                         6},
  {"genepop_RHWEachLocusEachPopulationProbabilityWithSettingsFile",        (DL_FUNC) &genepop_RHWEachLocusEachPopulationProbabilityWithSettingsFile,         3},
  {"genepop_RHWGlobalHD",                                                  (DL_FUNC) &genepop_RHWGlobalHD,                                                   5},
  {"genepop_RHWGlobalHDWithSettingsFile",                                  (DL_FUNC) &genepop_RHWGlobalHDWithSettingsFile,                                   3},
  {"genepop_RHWGlobalHE",                                                  (DL_FUNC) &genepop_RHWGlobalHE,                                                   5},
  {"genepop_RHWGlobalHEWithSettingsFile",                                  (DL_FUNC) &genepop_RHWGlobalHEWithSettingsFile,                                   3},
  {"genepop_RHWtableAlleleFrequenciesExpectedGenotypesFis",                (DL_FUNC) &genepop_RHWtableAlleleFrequenciesExpectedGenotypesFis,                 1},
  {"genepop_RHWtableHD",                                                   (DL_FUNC) &genepop_RHWtableHD,                                                    5},
  {"genepop_RHWtableHDWithSettingsFile",                                   (DL_FUNC) &genepop_RHWtableHDWithSettingsFile,                                    2},
  {"genepop_RHWtableHE",                                                   (DL_FUNC) &genepop_RHWtableHE,                                                    5},
  {"genepop_RHWtableHEWithSettingsFile",                                   (DL_FUNC) &genepop_RHWtableHEWithSettingsFile,                                    2},
  {"genepop_RHWtableProbability",                                          (DL_FUNC) &genepop_RHWtableProbability,                                           5},
  {"genepop_RHWtableProbabilityWithSettingsFile",                          (DL_FUNC) &genepop_RHWtableProbabilityWithSettingsFile,                           2},
  {"genepop_Rinterrupt_genepop",                                           (DL_FUNC) &genepop_Rinterrupt_genepop,                                            0},
  {"genepop_RIsolationByDistanceBetweenGroups",                            (DL_FUNC) &genepop_RIsolationByDistanceBetweenGroups,                            11},
  {"genepop_RIsolationByDistanceBetweenGroupsWithSettingsFile",            (DL_FUNC) &genepop_RIsolationByDistanceBetweenGroupsWithSettingsFile,             3},
  {"genepop_RIsolationByDistanceBetweenIndividuals",                       (DL_FUNC) &genepop_RIsolationByDistanceBetweenIndividuals,                       11},
  {"genepop_RIsolationByDistanceBetweenIndividualsWithSettingsFile",       (DL_FUNC) &genepop_RIsolationByDistanceBetweenIndividualsWithSettingsFile,        3},
  {"genepop_RNmEstimates",                                                 (DL_FUNC) &genepop_RNmEstimates,                                                  3},
  {"genepop_RNullAlleleEstimateAlleleFrequencies",                         (DL_FUNC) &genepop_RNullAlleleEstimateAlleleFrequencies,                          4},
  {"genepop_RNullAlleleEstimateAlleleFrequenciesWithSettingsFile",         (DL_FUNC) &genepop_RNullAlleleEstimateAlleleFrequenciesWithSettingsFile,          3},
  {"genepop_RPDGenicAllPairPopulationDifferentiation",                     (DL_FUNC) &genepop_RPDGenicAllPairPopulationDifferentiation,                      5},
  {"genepop_RPDGenicAllPairPopulationDifferentiationWithSettingsFile",     (DL_FUNC) &genepop_RPDGenicAllPairPopulationDifferentiationWithSettingsFile,      3},
  {"genepop_RPDGenicAllPopulationDifferentiation",                         (DL_FUNC) &genepop_RPDGenicAllPopulationDifferentiation,                          5},
  {"genepop_RPDGenicAllPopulationDifferentiationWithSettingsFile",         (DL_FUNC) &genepop_RPDGenicAllPopulationDifferentiationWithSettingsFile,          3},
  {"genepop_RPDGenotypicAllPairPopulationDifferentiation",                 (DL_FUNC) &genepop_RPDGenotypicAllPairPopulationDifferentiation,                  5},
  {"genepop_RPDGenotypicAllPairPopulationDifferentiationWithSettingsFile", (DL_FUNC) &genepop_RPDGenotypicAllPairPopulationDifferentiationWithSettingsFile,  3},
  {"genepop_RPDGenotypicAllPopulationDifferentiation",                     (DL_FUNC) &genepop_RPDGenotypicAllPopulationDifferentiation,                      5},
  {"genepop_RPDGenotypicAllPopulationDifferentiationWithSettingsFile",     (DL_FUNC) &genepop_RPDGenotypicAllPopulationDifferentiationWithSettingsFile,      3},
  {"genepop_RRandomSamplingOfHaploidGenotypesFromDiploidOnes",             (DL_FUNC) &genepop_RRandomSamplingOfHaploidGenotypesFromDiploidOnes,              2},
  {"genepop_RRelabelingAlleles",                                           (DL_FUNC) &genepop_RRelabelingAlleles,                                            2},
  {"genepop_Rset_restriction",                                             (DL_FUNC) &genepop_Rset_restriction,                                              1},
  {"genepop_setMantelSeed",                                                (DL_FUNC) &genepop_setMantelSeed,                                                 1},
  {"genepop_setRandomSeed",                                                (DL_FUNC) &genepop_setRandomSeed,                                                 1},
  {NULL, NULL, 0}
};

void R_init_genepop(DllInfo *dll)
{
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
}
